export {getHotelsByPrice} from  "./price-range"
export {getHotelsByRoomsAndBeds} from "./room-beds"
export {getHotelsByPropertyType} from "./property"
export {getHotelsByRatings} from "./ratings"
export {getHoteByCancalation} from "./hotel-cancel"